-- Ajouter les nouvelles valeurs à l'enum team_scope
-- À exécuter dans Supabase SQL Editor

ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'EITHER_TEAM';
ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'EITHER_OPPONENT';
ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'FAVOURITE_HOME';
ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'FAVOURITE_AWAY';
ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'UNDERDOG_HOME';
ALTER TYPE team_scope ADD VALUE IF NOT EXISTS 'UNDERDOG_AWAY';
